apiVersion: v1
kind: Secret
metadata:
  name: isgaarti-secrets
  namespace: isgaarti
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change_me"
  DATABASE_PASSWORD: "change_me"
  JWT_SECRET: "change_me_use_a_long_random_secret_at_least_32_characters"
  STRIPE_SECRET_KEY: "sk_test_or_live_xxx"
  STRIPE_PUBLISHABLE_KEY: "pk_test_or_live_xxx"
  IMAGEKIT_PRIVATE_KEY: "private_xxx"
